# Generated by Django 3.2.9 on 2021-12-06 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія для новин', 'verbose_name_plural': 'Категорії для новин'},
        ),
    ]
